# Generated by Django 5.2.7 on 2026-06-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_book_name_alter_event_name_alter_film_name_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='favorite_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='users',
            name='favorite_tags',
            field=models.ManyToManyField(blank=True, to='main.tag'),
        ),
    ]
