# Generated by Django 5.2.7 on 2026-05-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_game_music_series_gamereview_musicreview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('genre', 'Жанр'), ('game_genre', 'Игровой жанр'), ('setting', 'Сеттинг'), ('music_genre', 'Музыкальный жанр'), ('cuisine', 'Кухня')], max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='eventreview',
            options={'verbose_name': 'Отзыв на мероприятие', 'verbose_name_plural': 'Отзывы на мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='filmreview',
            options={'verbose_name': 'Отзыв на фильм', 'verbose_name_plural': 'Отзывы на фильмы'},
        ),
        migrations.AlterModelOptions(
            name='gamereview',
            options={'verbose_name': 'Отзыв на игру', 'verbose_name_plural': 'Отзывы на игры'},
        ),
        migrations.AlterModelOptions(
            name='musicreview',
            options={'verbose_name': 'Отзыв на музыку', 'verbose_name_plural': 'Отзывы на музыку'},
        ),
        migrations.AlterModelOptions(
            name='restaurantreview',
            options={'verbose_name': 'Отзыв на ресторан', 'verbose_name_plural': 'Отзывы на рестораны'},
        ),
        migrations.AlterModelOptions(
            name='seriesreview',
            options={'verbose_name': 'Отзыв на сериал', 'verbose_name_plural': 'Отзывы на сериалы'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='music',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='series',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='main.tag'),
        ),
        migrations.AddField(
            model_name='film',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='films', to='main.tag'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='games', to='main.tag'),
        ),
        migrations.AddField(
            model_name='music',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='music', to='main.tag'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='main.tag'),
        ),
        migrations.AddField(
            model_name='series',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='series', to='main.tag'),
        ),
    ]
