# Generated by Django 5.2.7 on 2026-05-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tag_alter_eventreview_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tags',
        ),
        migrations.AddField(
            model_name='game',
            name='game_genres',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'game_genre'}, related_name='games_by_genre', to='main.tag'),
        ),
        migrations.AddField(
            model_name='game',
            name='settings',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'setting'}, related_name='games_by_setting', to='main.tag'),
        ),
    ]
